all:
  hosts:
    debian:
      ansible_host: "{{ debian_host }}"
      
  vars:    
    ansible_user: "{{ debian_user }}"
    ansible_private_key_file: "{{ debian_private_key_file }}"
    ansible_port: "{{ debian_port }}"
    ansible_python_interpreter: "{{ ansible_python_interpreter }}"
