- block:
    - name: INSTALL DNS TOOLS
      apt:
        name:
          - whois
          - bind9utils
          - dnsutils
          - linkchecker
          - testssl.sh
        state: latest

    - name: INSTALL SCANNERS TOOLS
      apt:
        name:
          - traceroute
          - nikto
          - whatweb
        state: latest

    - name: INSTALL NETWORKS TOOLS
      apt:
        name:
          - telnet
          - nmap
          - etherape
          - ettercap-text-only
          - tcpdump
          - wireshark
          - aircrack-ng
          - cowpatty
        state: latest

    - name: INSTALL EXTRA TOOLS
      apt:
        name:
          - htop
          - mediainfo
          - stegosuite
          - crunch
          - exiftool
          - httrack
          - fping
          - masscan
          - iftop
          - hydra
          - chkrootkit
          - hping3
        state: latest

    - name: INSTALL ANDROID TOOLS
      apt:
        name:
          - apkinfo
          - apktool
        state: latest

    - name: INSTALL DEEP WEB TOOLS
      apt:
        name:
          - torbrowser-launcher
          - torsocks
          - tor
          - proxychains
          - proxytunnel
        state: latest

    - name: HARDENING TOOLS
      apt:
        name:
          - lynis
          - dnsdiag
        state: latest

    - name: DATABASES TOOLS
      apt:
        name:
          - sqlmap
          - sqlitebrowser
          - sqlite3
        state: latest
